### ISSUE TITLE
Node packages?

### ISSUE THREAD

**Issue by jbrooksuk** [Continuum-Editor/Continuum-Editor#90]
How come `node_modules` is committed to the source? This should usually be handled within `package.json`, but that seems to setup `nwjs` instead?

**Comment by DivineOmega** [comment]
You're very right. Thanks for reminding me about this. `nwjs` uses `package.json` for [its manifest](https://github.com/nwjs/nw.js/wiki/Manifest-format) which makes that rather unusual.

I'll see if I can combine the two format without issue and add a dependencies section for `npm install` to use. Hopefully it won't be a problem.

**Comment by DivineOmega** [comment]
Seems to work fine.

* `node_modules` directory remove
* `package.json` files changed to include dependencies and repository section
* build scripts for all OSes updated to run `npm install` when appropriate

**Comment by jbrooksuk** [comment]
👍🏻
